theme: jekyll-agency

url    : "https://www.rcmcooperative.com"
baseurl: ""

title      : RCM Cooperative
email      : cassandra.gouldvanpraag@rcmcooperative.com
description: "RCM Cooperative works with and for communities to develop and refine their capacity for equitable, resiliant and collaborative research."
author     : RCM Cooperative
logo:
  path: /assets/img/clients/rcmcoop-peach.png
  height: 60

locale: "en-US"

analytics:
  google:

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: 'blog'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  join:
    output: true
    permalink: /join/:path/
  team:
    output: true
    permalink: /team/:path/
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team-item"
  - scope:
      path: ""
      type: "join"
    values:
      layout: "join-item"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog-item"

markdown: kramdown